services:
  - type: web
    name: mp3tagger
    runtime: python
    buildCommand: "bash build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: ACOUSTID_API_KEY
        sync: false        # You set this manually in the Render dashboard
      - key: FLASK_ENV
        value: production
